import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/transaction_model.dart';
import '../models/income_record_model.dart';
import '../models/expense_record_model.dart';
import '../theme/app_theme.dart';
import '../utils/date_formatter.dart';

class ReportService {
  static pw.Font? _cachedFont;

  Future<pw.Font> _loadFont() async {
    if (_cachedFont != null) return _cachedFont!;
    final data =
        await rootBundle.load('assets/fonts/Ebrima.ttf');
    _cachedFont = pw.Font.ttf(data);
    return _cachedFont!;
  }

  
  Future<void> generateTransactionReport(
    List<MoneyTransaction> transactions,
    List<IncomeRecord> incomeRecords,
    List<ExpenseRecord> expenseRecords,
    String dateRange,
    String typeFilter,
  ) async {
    debugPrint('Generating PDF report for ${transactions.length} transactions, '
        '${incomeRecords.length} income records, '
        '${expenseRecords.length} expense records');
    try {
      final amharicFont = await _loadFont();
      final pdf = pw.Document();
      final now = DateTime.now();
      const brand = AppColors.primary;
      final brandPdf = PdfColor(brand.r, brand.g, brand.b);
      final brandTint = PdfColor(brand.r, brand.g, brand.b, 0.08);
      final brandBorder = PdfColor(brand.r, brand.g, brand.b, 0.3);
      final currencyFormatter =
          NumberFormat.currency(symbol: 'ETB ', decimalDigits: 2);

      
      double totalDistributed = 0;
      double totalReturned = 0;
      double totalPurchased = 0;

      for (var t in transactions) {
        if (t.type == 'distribution') {
          totalDistributed += t.amount;
        } else if (t.type == 'return') {
          totalReturned += t.amount;
        } else if (t.type == 'purchase') {
          totalPurchased += t.amount;
        }
      }

      double totalInvestment = 0;
      double totalSales = 0;
      for (var r in incomeRecords) {
        if (r.kind == IncomeKind.investment) {
          totalInvestment += r.amount;
        } else {
          totalSales += r.amount;
        }
      }

      double totalExpenses = 0;
      for (var e in expenseRecords) {
        totalExpenses += e.amount;
      }

      final netFlow = totalDistributed -
          totalReturned +
          totalInvestment +
          totalSales -
          totalExpenses;

      final totalRecords =
          transactions.length + incomeRecords.length + expenseRecords.length;

      List<List<String>> rows = [];
      for (var t in transactions) {
        rows.add([
          DateFormatter.formatDateTime(t.createdAt),
          t.workerName.isNotEmpty ? t.workerName : 'Unknown',
          t.typeDisplay,
          currencyFormatter.format(t.amount),
        ]);
      }
      for (var r in incomeRecords) {
        rows.add([
          DateFormatter.formatDateTime(r.createdAt),
          r.kind == IncomeKind.investment
              ? (r.viewerName ?? 'Investment')
              : (r.saleCategory ?? 'Sale'),
          r.kind == IncomeKind.investment ? 'Investment' : 'Sale',
          currencyFormatter.format(r.amount),
        ]);
      }
      for (var e in expenseRecords) {
        rows.add([
          DateFormatter.formatDateTime(e.createdAt),
          e.expenseCategory,
          'Expense',
          currencyFormatter.format(e.amount),
        ]);
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          theme: pw.ThemeData.withFont(base: amharicFont, bold: amharicFont),
          footer: (pw.Context context) {
            return pw.Column(
              children: [
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Generated by Cofiz App',
                        style: const pw.TextStyle(
                            fontSize: 10, color: PdfColors.grey)),
                    pw.Text(
                        'Page ${context.pageNumber} of ${context.pagesCount}',
                        style: const pw.TextStyle(
                            fontSize: 10, color: PdfColors.grey)),
                  ],
                ),
              ],
            );
          },
          build: (pw.Context context) {
            final summaryRows = <(String, double)>[
              ('Distributed', totalDistributed),
              ('Returned', totalReturned),
              ('Coffee Purchase', totalPurchased),
              ('Investment', totalInvestment),
              ('Sales', totalSales),
              ('Expenses', totalExpenses),
              ('Net Flow', netFlow),
            ];

            return [
              
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Cofiz Report',
                        style: pw.TextStyle(
                            fontSize: 24,
                            fontWeight: pw.FontWeight.bold,
                            color: brandPdf)),
                    pw.Text(DateFormatter.formatDateTime(now),
                        style: const pw.TextStyle(fontSize: 12)),
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: brandTint,
                  border: pw.Border.all(color: brandBorder),
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(5)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Report Criteria',
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 5),
                    pw.Text('Date Range: $dateRange'),
                    pw.Text('Type Filter: $typeFilter'),
                    pw.Text('Total Records: $totalRecords'),
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              
              pw.Text('Summary',
                  style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: brandPdf)),
              pw.SizedBox(height: 10),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                columnWidths: const {
                  0: pw.FlexColumnWidth(1),
                  1: pw.FlexColumnWidth(2),
                },
                children: [
                  for (final row in summaryRows)
                    pw.TableRow(
                      decoration: pw.BoxDecoration(
                        color: row.$1 == 'Net Flow'
                            ? brandPdf
                            : PdfColors.white,
                      ),
                      children: [
                        pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(
                              horizontal: 12, vertical: 8),
                          child: pw.Text(
                            row.$1,
                            style: pw.TextStyle(
                              fontSize: row.$1 == 'Net Flow' ? 13 : 11,
                              fontWeight: row.$1 == 'Net Flow'
                                  ? pw.FontWeight.bold
                                  : pw.FontWeight.normal,
                              color: row.$1 == 'Net Flow'
                                  ? PdfColors.white
                                  : PdfColors.black,
                            ),
                          ),
                        ),
                        pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(
                              horizontal: 12, vertical: 8),
                          child: pw.Text(
                            currencyFormatter.format(row.$2),
                            textAlign: pw.TextAlign.right,
                            style: pw.TextStyle(
                              fontSize: row.$1 == 'Net Flow' ? 13 : 11,
                              fontWeight: row.$1 == 'Net Flow'
                                  ? pw.FontWeight.bold
                                  : pw.FontWeight.normal,
                              color: row.$1 == 'Net Flow'
                                  ? PdfColors.white
                                  : PdfColors.black,
                            ),
                          ),
                        ),
                      ],
                    ),
                ],
              ),

              pw.SizedBox(height: 20),

              
              pw.Text('Transactions',
                  style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: brandPdf)),
              pw.SizedBox(height: 10),
              pw.TableHelper.fromTextArray(
                context: context,
                headers: ['Date', 'Name', 'Type', 'Amount'],
                data: rows,
                headerStyle: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: pw.BoxDecoration(color: brandPdf),
                rowDecoration: const pw.BoxDecoration(
                    border: pw.Border(
                        bottom: pw.BorderSide(color: PdfColors.grey300))),
                cellAlignment: pw.Alignment.centerLeft,
                cellAlignments: {
                  3: pw.Alignment.centerRight,
                },
              ),

              pw.SizedBox(height: 0),
            ];
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'Cofiz_Report_${DateFormat('yyyyMMdd_HHmm').format(now)}',
      );
    } catch (e, stack) {
      debugPrint('Error in ReportService: $e');
      debugPrint('$stack');
      rethrow;
    }
  }
}
